-- Migracao para suporte multi-usuario
-- Atribui todos os dados existentes ao usuario "admin"
-- Pre-requisito: usuario com username='admin' deve existir na tabela `users`

SET @adminId = (SELECT id FROM users WHERE username = 'admin' LIMIT 1);

-- Aborta a execucao se nao houver usuario admin
SELECT IF(@adminId IS NULL,
          (SELECT CONCAT('ERRO: usuario admin nao encontrado em users. Crie o admin antes de executar esta migration.')
           FROM information_schema.tables WHERE 1=0),
          'OK') AS preflight;

-- ATIVO_CARTEIRA
ALTER TABLE ATIVO_CARTEIRA ADD COLUMN ID_USUARIO BIGINT NULL;
UPDATE ATIVO_CARTEIRA SET ID_USUARIO = @adminId WHERE ID_USUARIO IS NULL;
ALTER TABLE ATIVO_CARTEIRA MODIFY COLUMN ID_USUARIO BIGINT NOT NULL;
ALTER TABLE ATIVO_CARTEIRA ADD CONSTRAINT fk_ativo_carteira_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id);

-- OPERACAO_RENDA_VARIAVEL
ALTER TABLE OPERACAO_RENDA_VARIAVEL ADD COLUMN ID_USUARIO BIGINT NULL;
UPDATE OPERACAO_RENDA_VARIAVEL SET ID_USUARIO = @adminId WHERE ID_USUARIO IS NULL;
ALTER TABLE OPERACAO_RENDA_VARIAVEL MODIFY COLUMN ID_USUARIO BIGINT NOT NULL;
ALTER TABLE OPERACAO_RENDA_VARIAVEL ADD CONSTRAINT fk_op_rv_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id);

-- OPERACAO_RENDA_FIXA
ALTER TABLE OPERACAO_RENDA_FIXA ADD COLUMN ID_USUARIO BIGINT NULL;
UPDATE OPERACAO_RENDA_FIXA SET ID_USUARIO = @adminId WHERE ID_USUARIO IS NULL;
ALTER TABLE OPERACAO_RENDA_FIXA MODIFY COLUMN ID_USUARIO BIGINT NOT NULL;
ALTER TABLE OPERACAO_RENDA_FIXA ADD CONSTRAINT fk_op_rf_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id);

-- EVENTO_RENDA_VARIAVEL
ALTER TABLE EVENTO_RENDA_VARIAVEL ADD COLUMN ID_USUARIO BIGINT NULL;
UPDATE EVENTO_RENDA_VARIAVEL SET ID_USUARIO = @adminId WHERE ID_USUARIO IS NULL;
ALTER TABLE EVENTO_RENDA_VARIAVEL MODIFY COLUMN ID_USUARIO BIGINT NOT NULL;
ALTER TABLE EVENTO_RENDA_VARIAVEL ADD CONSTRAINT fk_ev_rv_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id);

-- EVENTO_RENDA_FIXA
ALTER TABLE EVENTO_RENDA_FIXA ADD COLUMN ID_USUARIO BIGINT NULL;
UPDATE EVENTO_RENDA_FIXA SET ID_USUARIO = @adminId WHERE ID_USUARIO IS NULL;
ALTER TABLE EVENTO_RENDA_FIXA MODIFY COLUMN ID_USUARIO BIGINT NOT NULL;
ALTER TABLE EVENTO_RENDA_FIXA ADD CONSTRAINT fk_ev_rf_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id);

-- APORTE
ALTER TABLE APORTE ADD COLUMN ID_USUARIO BIGINT NULL;
UPDATE APORTE SET ID_USUARIO = @adminId WHERE ID_USUARIO IS NULL;
ALTER TABLE APORTE MODIFY COLUMN ID_USUARIO BIGINT NOT NULL;
ALTER TABLE APORTE ADD CONSTRAINT fk_aporte_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id);

-- HISTORICO_ATIVO_CARTEIRA
ALTER TABLE HISTORICO_ATIVO_CARTEIRA ADD COLUMN ID_USUARIO BIGINT NULL;
UPDATE HISTORICO_ATIVO_CARTEIRA SET ID_USUARIO = @adminId WHERE ID_USUARIO IS NULL;
ALTER TABLE HISTORICO_ATIVO_CARTEIRA MODIFY COLUMN ID_USUARIO BIGINT NOT NULL;
ALTER TABLE HISTORICO_ATIVO_CARTEIRA ADD CONSTRAINT fk_hist_ac_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id);

-- PREJUIZO_ACUMULADO
ALTER TABLE prejuizo_acumulado ADD COLUMN ID_USUARIO BIGINT NULL;
UPDATE prejuizo_acumulado SET ID_USUARIO = @adminId WHERE ID_USUARIO IS NULL;
ALTER TABLE prejuizo_acumulado MODIFY COLUMN ID_USUARIO BIGINT NOT NULL;
ALTER TABLE prejuizo_acumulado ADD CONSTRAINT fk_prej_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id);

-- ATIVO: NULL = renda variavel (compartilhado); preenchido = renda fixa do usuario
ALTER TABLE ATIVO ADD COLUMN ID_USUARIO BIGINT NULL;
UPDATE ATIVO a
   SET a.ID_USUARIO = @adminId
 WHERE a.ID_USUARIO IS NULL
   AND EXISTS (SELECT 1 FROM PARAMETRO_RENDA_FIXA p WHERE p.ID_ATIVO = a.ID_ATIVO);
ALTER TABLE ATIVO ADD CONSTRAINT fk_ativo_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id);
