-- Cria tabela ALOCACAO_META com percentuais de alocacao alvo por usuario.
-- Faz seed dos defaults (30/30/30/10) para todos os usuarios ja existentes.

CREATE TABLE IF NOT EXISTS ALOCACAO_META (
    ID_ALOCACAO_META BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO       BIGINT NOT NULL,
    DS_CATEGORIA     VARCHAR(30) NOT NULL,
    QT_PERCENTUAL    DOUBLE NOT NULL,
    CONSTRAINT fk_alocacao_meta_user FOREIGN KEY (ID_USUARIO) REFERENCES users(id),
    CONSTRAINT uk_alocacao_meta_user_categoria UNIQUE (ID_USUARIO, DS_CATEGORIA)
);

INSERT INTO ALOCACAO_META (ID_USUARIO, DS_CATEGORIA, QT_PERCENTUAL)
SELECT u.id, 'ACOES', 30.0 FROM users u
WHERE NOT EXISTS (SELECT 1 FROM ALOCACAO_META m WHERE m.ID_USUARIO = u.id AND m.DS_CATEGORIA = 'ACOES');

INSERT INTO ALOCACAO_META (ID_USUARIO, DS_CATEGORIA, QT_PERCENTUAL)
SELECT u.id, 'FIIS', 30.0 FROM users u
WHERE NOT EXISTS (SELECT 1 FROM ALOCACAO_META m WHERE m.ID_USUARIO = u.id AND m.DS_CATEGORIA = 'FIIS');

INSERT INTO ALOCACAO_META (ID_USUARIO, DS_CATEGORIA, QT_PERCENTUAL)
SELECT u.id, 'RENDA_FIXA', 30.0 FROM users u
WHERE NOT EXISTS (SELECT 1 FROM ALOCACAO_META m WHERE m.ID_USUARIO = u.id AND m.DS_CATEGORIA = 'RENDA_FIXA');

INSERT INTO ALOCACAO_META (ID_USUARIO, DS_CATEGORIA, QT_PERCENTUAL)
SELECT u.id, 'RENDA_INTERNACIONAL', 10.0 FROM users u
WHERE NOT EXISTS (SELECT 1 FROM ALOCACAO_META m WHERE m.ID_USUARIO = u.id AND m.DS_CATEGORIA = 'RENDA_INTERNACIONAL');
